### ISSUE TITLE
Car will not turn off

### ISSUE THREAD

**Issue by drhannibalseca** [Vasia92LTU/dv-speedo#1]
Hello

I use Cdn-Fuel and have the option to leave the car on when exiting,if you hold F the car will turn off or while in the car hit key G.
With your hud none of the worksand the car just says on.
Any work around I can do?

**Comment by Vasia92LTU** [comment]
I think it depends on other scripts. Check your qb-smallresource or qb-vehiclekeys  maybe there you will find toggle engine issue. Or try to use different script
